# Generated by Django 4.2.2 on 2023-07-04 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credential', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='average_cost',
            new_name='average_price',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='market_value',
            new_name='total_price',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='todays_return',
        ),
    ]
