# Generated by Django 4.2.2 on 2023-07-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credential', '0003_purchasedstock_ticker_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedstock',
            name='total_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
