# Generated by Django 4.2.2 on 2023-07-04 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credential', '0004_purchasedstock_total_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasedstock',
            name='total_value',
        ),
    ]
